# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

sun:
cloud: !include cloud_config.yaml
scene: !include scenes.yaml
group: !include groups.yaml
script: !include scripts.yaml
switch: !include_dir_list switches
stream:
automation: !include automations.yaml
wake_on_lan:
