title: Home
#
custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
#
resources: !include_dir_list lovelace/resources
#
views:
  - !include lovelace/views/main.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/living_room.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/cameras.yaml