esphome:
  name: main_desk_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "WiFi"
  password: !secret WiFi_Password
  fast_connect: on

  ap:
    ssid: "Main desk light Fallback Hotspot"
    password: !secret AP_Password

captive_portal:

logger:

api:

ota:
  safe_mode: True
  password: !secret OTA_Password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Main desk light button"
    on_press:
      - light.toggle: light_relay

output:
  - platform: esp8266_pwm
    id: sonoff_relay
    pin:
      number: GPIO12
      inverted: false

light:
  - platform: binary
    name: "Main desk light"
    output: sonoff_relay
    id: light_relay

sensor:
  - platform: wifi_signal
    name: "Main desk light WiFi signal"
    update_interval: 60s
  - platform: uptime
    name: "Main desk light uptime"

text_sensor:
  - platform: version
    name: "Main desk light ESPHome version"
